### ISSUE TITLE
Custom Package contains highlight.js without any language support

### ISSUE THREAD

**Issue by DrTobe** [highlightjs/highlightjs.org#5]
When I download a "custom package" from https://highlightjs.org/download/, the downloaded archive contains the correct `highlight.min.js` but a wrong `highlight.js`. The contained `highlight.js` does not seem to support any languages on its own. I guess they could be configured/enabled afterwards manually, but since I was downloading a custom package I was assuming that the contained `highlight.js` would already support all I need/want.

Being neither a `highlight.js` nor a JS expert, it took me a few minutes to figure this out. I guess it would be nicer if
1. the downloaded archive does not contain the `highlight.js` at all, only the `highlight.min.js` would be sufficient, or
2. the `highlight.js` supports all selected languages automatically, or
3. this behaviour was documented next to the download link.

After having realized that I just needed to use the minified version, everything worked like a charm. So in general, this seems to work nicely and I like the feature.

**Comment by joshgoebel** [comment]
if we make changes here I think the correct solution might be to rename the build asset, ie `custom-highlight.min.js`... leaving the original in place and unmodified.

Thoughts?
